// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'firebase_options.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPvv5TuvcIeMo8TGaWCa8rKHJVECIVhRc',
    appId: '1:896355687998:web:2ae87314411b80fee1bb6f',
    messagingSenderId: '896355687998',
    projectId: 'easyvahan-b6dbf',
    authDomain: 'easyvahan-b6dbf.firebaseapp.com',
    storageBucket: 'easyvahan-b6dbf.appspot.com',
    measurementId: 'G-33B3K2YBDY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzYp-MA4VGryCyNyWOi_OJQQd6yg-shnE',
    appId: '1:896355687998:android:98514418af12511fe1bb6f',
    messagingSenderId: '896355687998',
    projectId: 'easyvahan-b6dbf',
    storageBucket: 'easyvahan-b6dbf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUzuyOKdF9dI7B8vvMrQkf3kFSP05gGDc',
    appId: '1:896355687998:ios:5bc80e4a680a012be1bb6f',
    messagingSenderId: '896355687998',
    projectId: 'easyvahan-b6dbf',
    storageBucket: 'easyvahan-b6dbf.appspot.com',
    iosClientId: '896355687998-neonsinvj6vq6tqo7sp5l7kvhp9vmlon.apps.googleusercontent.com',
    iosBundleId: 'com.example.easyVahan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUzuyOKdF9dI7B8vvMrQkf3kFSP05gGDc',
    appId: '1:896355687998:ios:495de4013a8ce7d5e1bb6f',
    messagingSenderId: '896355687998',
    projectId: 'easyvahan-b6dbf',
    storageBucket: 'easyvahan-b6dbf.appspot.com',
    iosClientId: '896355687998-r2lt7k9q1ofun9lab44r5vmie84f0th0.apps.googleusercontent.com',
    iosBundleId: 'com.example.easyVahan.RunnerTests',
  );
}
