// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSdE_Jtx-lTAwi7f9GN9SE5UNBbfYaglU',
    appId: '1:268235194950:web:7fcff2a6589abcefbe0047',
    messagingSenderId: '268235194950',
    projectId: 'easy-vahan',
    authDomain: 'easy-vahan.firebaseapp.com',
    storageBucket: 'easy-vahan.appspot.com',
    measurementId: 'G-4YMN9EQYDK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIb0LWIBiObZl1-XV1rhRYYiBv4TNf6pE',
    appId: '1:268235194950:android:c170ae4e1801d0b8be0047',
    messagingSenderId: '268235194950',
    projectId: 'easy-vahan',
    storageBucket: 'easy-vahan.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8jRoBEnX6MadAlTwTTk6ZnBhFFscHNWU',
    appId: '1:268235194950:ios:327b76d0bff1670bbe0047',
    messagingSenderId: '268235194950',
    projectId: 'easy-vahan',
    storageBucket: 'easy-vahan.appspot.com',
    iosBundleId: 'com.example.easyVahan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8jRoBEnX6MadAlTwTTk6ZnBhFFscHNWU',
    appId: '1:268235194950:ios:876f0b01240ba67bbe0047',
    messagingSenderId: '268235194950',
    projectId: 'easy-vahan',
    storageBucket: 'easy-vahan.appspot.com',
    iosBundleId: 'com.example.easyVahan.RunnerTests',
  );
}
